=== JVM-Squad/autoscan-rest-application/bpmn-process/src/main/resources/schema/profile.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://www.pledger.io/schemas/profile.schema.json",
  "title": "Profile",
  "type": "object",
  "properties": {
    "accounts": {
      "type": "array",
      "items": {
        "ref": "https://www.pledger.io/schemas/account.schema.json"
      }
    },
    "categories": {
      "type": "array",
      "items": {
        "$ref": "https://www.pledger.io/schemas/category.schema.json"
      }
    },
    "contracts": {
      "type": "array",
      "items": {
        "$ref": "https://www.pledger.io/schemas/contract.schema.json"
      }
    },
    "rules": {
      "type": "array",
      "items": {
        "$ref": "https://www.pledger.io/schemas/rule.schema.json"
      }
    },
    "budgetPeriods": {
      "type": "array",
      "items": {
        "$ref": "https://www.pledger.io/schemas/budget.schema.json"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "transactions": {
      "type": "array",
      "items": {
        "$ref": "https://www.pledger.io/schemas/transaction.schema.json"
      }
    }
  }
}

=== JVM-Squad/autoscan-rest-application/bpmn-process/src/test/resources/profile-test/profile-export.json
{
  "accounts": [
    {
      "name": "Demo checking account",
      "description": null,
      "currency": "EUR",
      "iban": null,
      "bic": null,
      "number": null,
      "type": "default"
    },
    {
      "name": "Groceries are us",
      "description": null,
      "currency": "EUR",
      "iban": null,
      "bic": null,
      "number": null,
      "type": "creditor"
    },
    {
      "name": "Boss & Co.",
      "description": null,
      "currency": "EUR",
      "iban": null,
      "bic": null,
      "number": null,
      "type": "debtor"
    }
  ],
  "rules": [
    {
      "name": "Income locator",
      "description": null,
      "restrictive": true,
      "active": true,
      "sort": 0,
      "group": null,
      "conditions": [
        {
          "field": "AMOUNT",
          "operation": "MORE_THAN",
          "value": "2000"
        },
        {
          "field": "AMOUNT",
          "operation": "LESS_THAN",
          "value": "5000"
        },
        {
          "field": "DESCRIPTION",
          "operation": "CONTAINS",
          "value": "Salary"
        }
      ],
      "changes": [
        {
          "field": "CATEGORY",
          "value": "Salary"
        }
      ]
    },
    {
      "name": "Groceries matcher",
      "description": null,
      "restrictive": true,
      "active": true,
      "sort": 0,
      "group": null,
      "conditions": [
        {
          "field": "DESCRIPTION",
          "operation": "CONTAINS",
          "value": "grocery"
        },
        {
          "field": "AMOUNT",
          "operation": "MORE_THAN",
          "value": "20"
        },
        {
          "field": "AMOUNT",
          "operation": "LESS_THAN",
          "value": "90"
        }
      ],
      "changes": [
        {
          "field": "CATEGORY",
          "value": "Groceries"
        },
        {
          "field": "TO_ACCOUNT",
          "value": "Groceries are us"
        }
      ]
    }
  ],
  "categories": [
    {
      "label": "Salary",
      "description": "Income by salary"
    },
    {
      "label": "Groceries",
      "description": "Spending on groceries"
    },
    {
      "label": "Car",
      "description": "Spending on car"
    }
  ],
  "budgetPeriods": [],
  "contracts": [],
  "tags": []
}
